# Generated by Django 4.1.7 on 2023-04-05 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
